/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int add_fun(int a, int b, int c, int d){
	return a+b+c+d;
}

int main(void)
{
	int val = 20;
	int ret;
	ret = add_fun(1,2,3,4);    //fxn callon
	printf("Result is  =  %d\n",val);   //test to increase text size in  Build Analyzer(memory details)
	printf("Result is  =  %d\n",ret);



    /* Loop forever */
	for(;;);
}
