/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int add(int input_i, int input_j){
	int result = 0;
	//__asm volatile("ADD %0, %1, %2":"=r"(res):"r"(i),"r"(j));     //methos 1
	__asm volatile("ADD %[result], %[input_i], %[input_j]"          //method2
			:[result]"=r"(result)
			 :[input_i]"r"(input_i), [input_j]"r"(input_j)
			  );
}

int main(void)
{
    /* Loop forever */
	/*//My approach
	 * int sum(int a, int b){
	return a+b;
   }
	int c=0;
	c = sum(10,20);
	//int o=0;
	//o = printf("%d",o);
	__asm volatile("ADD %0, %1":"=r"(c):"r"(sum(10,20)));
	*/

	int a=1;
	int b=2;
	int c = 0;
	c = add(a,b);


	for(;;);
}
